version: '3.9'

services:
  backend:
    build: .
    container_name: book-backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/book_exchange
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: book-db
    restart: always
    environment:
      POSTGRES_DB: book_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
